name: dictionary
description: "This is a challenge by Coodesh"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  sqflite: ^2.3.3+1
  json_annotation: ^4.9.0
  either_dart: ^1.0.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.3
  get_storage: ^2.1.1
  validatorless: ^1.2.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/words_dictionary.json
